### ISSUE TITLE
tap-linkedin-ads should fetch campaign & campaign_groups automatically.

### ISSUE THREAD

**Issue by haleemur** [MeltanoLabs/tap-linkedin-ads#102]
# Summary

Currently, meltano variant tap-linkedin-ads requires the user to specify the campaign & campgain_group. However these are likely to evolve over time and not something that should be hard coded into the extraction confuration.

I looked at the [singer-io variant](https://github.com/singer-io/tap-linkedin-ads), and that tap allows for the campaign & campaign group to not be hard coded. It actually fetches all campaign & campaign groups for the user

# Proposal

The meltano variant tap should also fetch the campaign & campaign groups similar to the singer-io variant.

**Comment by pnadolny13** [comment]
Closed by https://github.com/MeltanoLabs/tap-linkedin-ads/pull/104
